### ISSUE TITLE
MakeReleaseNotes.genPR throws exception

### ISSUE THREAD

**Issue by peter-empen** [scala/make-release-notes#122]
Under Windows I get

java.util.NoSuchElementException: key not found: HOME
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:58)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:58)
        at MakeReleaseNotes$.genPR$default$4(MakeReleaseNotes.scala:8)

and after setting HOME I get

java.lang.IllegalArgumentException
        at java.util.Date.parse(Unknown Source)
        at java.util.Date.<init>(Unknown Source)
        at MakeReleaseNotes$.genPR(MakeReleaseNotes.scala:9)

So I cannot add my library:(.

Thanks, Peter

**Comment by adriaanm** [comment]
Hi, sorry about that -- the code in this repo is not really meant to work except on our machines..

The good news: to add your library, simply go to https://github.com/scala/make-release-notes/edit/master/hand-written.md and submit a PR from your browser :-)
